### PR TITLE
Here is my review for your R Assignment

### PR DESCRIPTION
**Pull request by Ntopping**

### CODE REVIEW

**Comment by Ntopping** [comment]
Don't know why I closed the request

**Comment by visheshbhatia26** [comment]
No worries!

**Comment by visheshbhatia26** [comment]
Hi Nick, 

Thank you so much for the reply. When you cloned the forked repository to your R studio, did you choose New Project -> Version Control -> Git and then copied the link there?

**Comment by Ntopping** [comment]
That is exactly what I did. Then you can make your file and push the changes to your forked repository like how you've been doing with your assignment. And for clarity's sake, the link you want would be for the forked repository, not their repository for their actual assignment.

**Comment by visheshbhatia26** [comment]
Yes, thank you so much! I appreciate all your help.

**Comment by visheshbhatia26** [comment]
Once you add the file, you commit the changes and then you press push in R studio. Do you have to create a pull request too or does that automatically get generated?

**Comment by Ntopping** [comment]
Yes, the last step is to initiate the pull request.

**Pull request merged**
